apiVersion: v1
kind: Service
metadata:
  name: notification-system-service
spec:
  selector:
    app: notification-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
